name: Continuous Integration Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm test
  deploy:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || contains(github.ref, 'refs/tags/')) }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Env Config - Stable
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID_STABLE }}" >> $GITHUB_ENV

      - name: Env Config - Dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          short_sha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "VERSION=dev-${short_sha}" >> $GITHUB_ENV
          echo "NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID_DEV }}" >> $GITHUB_ENV

      - name: Add n64 toolchain repo
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://practicerom.com/public/packages/debian staging main
          repo-name: practicerom
          keys-asc: https://practicerom.com/public/packages/debian/pgp.pub

      - name: Add n64 toolchain
        run: sudo apt-get install n64-ultra

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm i

      - name: Build
        run: |
          npm run build

      - name: Deploy to netlify
        run: |
          npm i -g netlify-cli
          cd packages/gui/dist && netlify deploy --filter @ootmm/gui --prod --dir ./
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
